<div class="bgimg img-lake">
    <div class="topleft">
        <b>Сервер:</b><br>
		<b>109.194.35.237:55555</b>
    </div>
    <div class="main_logo"> </div>
    <div class="topright">
   	<a href="?action=logout">Выйти</a>
    </div>
    <div class="container_middle_left">
        <b>Статус сервера: </b>
        <form action="php.php">
            <button type="submit" class="btn login">Запустить</button>
        </form>
    </div>
    <div class="container_middle_right">
	<b>Список модификаций:</b>
    </div>
</div>
